game:
  minimum-players: 2 #Amount needed to start the game.
messages:
  prefix: "&8❚&b Splegg &8❚&r "
  join: "%player% &7has joined AmbaSplegg."
  quit: "%player% &7has quit AmbaSplegg."
  waiting:
    - "&ePlayers waiting: &6%amountWaiting%"
    - "&ePlayers needed to start: &6%amountNeeded%"
    - "&eTime till start: &6%timer%"
  vote: "&e&lVote for a map! &7Use &f/v #."
  voteoption: "&e&l%#%. &6%map% &7[&f%amountVotes% &7Votes]"
  voted: "&3Voting has ended! &bThe map &f%mapVoted% &bhas won!" #TODO tie vote
  start:
    - "&7&m                    &b&l Splegg &7&m                    "
    - ""
    - "&9Eggs destroy blocks."
    - "&eRight click your gun to shoot eggs."
    - "&dCollect Powerups (Enderchests) for special abilities."
    - "&3Be the last player standing!"
    - ""
    - "&7&m                                                "
  restart: "&cGame Over &7» &3&lGoing to hub in 10 seconds."
  thanks:
    - "&7&m                                                "
    - "&6Thank you for playing AmbaGames!"
    - ""
    - "&7&m                                                "
splegg-messages:
  eliminated: "%player% has been &c&beliminated!"
  finish:
    - "&7&m                 &c&l Game. OVER! &7&m                  "
    - ""
    - "%winner% &7has won!"
    #TODO- "%playerMostBlocks% &2destroyed the most blocks! &a(%mostBlocksAmount% blocks)"
    #TODO- "%playerMostEggs% &6shot the most eggs! &e(%mostEggsAmount% eggs)"
    - ""
    - "&7&m                                                "
maps:
  beyblade:
    name: "Beyblade"
    spawns:
      1:
        x: 0
        y: 100
        z: 0
      2:
        x: 3
        y: 100
        z: 3
  bigtrees:
    name: "Big Trees"
    spawns:
      1:
        x: 0
        y: 100
        z: 0
  djskeyboard:
    name: "DJ's Keyboard"
  dragonblade:
    name: "Dragon Blade"
  theblade:
    name: "The Blade"
  thespace:
    name: "The Space"