game:
  minimum-players: 1 #Amount needed to start the game.
  vote-amount: 6 #Amount of maps to load into the game, must be less than the amount in maps.
  duration: 600 #Amount of seconds for the game to automatically finish.
messages:
  chat: "&8» &r%message%"
  prefix: "&8❚&b Splegg &8❚&r "
  join: "%player% &7has joined AmbaSplegg."
  quit: "%player% &7has quit AmbaSplegg."
  waiting:
    - "&ePlayers waiting: &6%amountWaiting%"
    - "&ePlayers needed to start: &6%amountNeeded%"
    - "&eTime till start: &6%timer% &eseconds"
  vote: "&e&lVote for a map! &7Use &f/v #."
  voteselect: "&a&lVote received. &3The map &6%map% &3now has &b%amountVotes% &3votes."
  voteoption: "&e&l%#%. &6%map% &7[&f%amountVotes% &7Votes]"
  voted: "&3Voting has ended! &bThe map &f%mapVoted% &bhas won!" #TODO tie vote
  start:
    - "&7&m                    &b&l Splegg &7&m                    "
    - ""
    - "&9Eggs destroy blocks."
    - "&eRight click your gun to shoot eggs."
    - "&dCollect Powerups (Enderchests) for special abilities."
    - "&3Be the last player standing!"
    - ""
    - "&7&m                                                "
  restart: "&cGame Over &7» &3&lGoing to hub in 10 seconds."
  thanks:
    - "&7&m                                                "
    - "&6Thank you for playing AmbaGames!"
    - ""
    - "&7&m                                                "
splegg-messages:
  eliminated: "%player% has been &c&beliminated!"
  finish:
    - "&7&m                 &c&l Game. OVER! &7&m                  "
    - ""
    - "%winner% &7has won!"
    #TODO- "%playerMostBlocks% &2destroyed the most blocks! &a(%mostBlocksAmount% blocks)"
    #TODO- "%playerMostEggs% &6shot the most eggs! &e(%mostEggsAmount% eggs)"
    - ""
    - "&7&m                                                "
maps:
  beyblade:
    name: "Beyblade"
    spawns:
      1:
        x: 12
        y: 62
        z: 12
      2:
        x: -12
        y: 62
        z: 12
      3:
        x: 12
        y: 62
        z: -12
      4:
        x: -12
        y: 62
        z: -12
  bigtrees:
    name: "Big Trees"
    spawns:
      1:
        x: 0
        y: 100
        z: 0
  djskeyboard:
    name: "DJ's Keyboard"
  dragonblade:
    name: "Dragon Blade"
  theblade:
    name: "The Blade"
  thespace:
    name: "The Space"